config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "loans/new"
  get "loans/create"
  # A página de login é a nova raiz da aplicação
  root 'sessions#new'

  # Rotas de login/logout para bibliotecários
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Rota para alteração de senha de primeiro acesso do bibliotecário
  get 'edit_password', to: 'password_changes#edit'
  patch 'edit_password', to: 'password_changes#update'

  # --- Área do Bibliotecário Padrão ---
  get 'dashboard', to: 'books#index'

  resources :books do
    resources :loans, only: [:new, :create]
  end

  resources :loans, only: [] do
    member do
      get :details # Rota para obter os detalhes do empréstimo (para o pop-up)
      patch :return_book # Rota para marcar o livro como devolvido
    end
  end

  resources :categories, except: [:show]
  resources :users, only: [:index, :new, :create]

  # --- Área do Administrador ---
  namespace :admin do
    resources :librarians, only: [:index, :new, :create, :destroy]
  end

  resources :password_resets, only: [:new, :create, :edit, :update], param: :token
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # Garante que o usuário deve estar logado para acessar qualquer página aqui
  before_action :require_login

  def index
    # Esta página irá simplesmente renderizar a view 'index.html.erb'
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1>Bem-vindo à Biblioteca Municipal</h1>

<% if Current.librarian.admin? %>
  <p>Você está na área do administrador.</p>
  <p><%= link_to 'Gerenciar Bibliotecários', admin_librarians_path, class: 'btn-primary' %></p>
<% else %>
  <p>Você está na área de gerenciamento do acervo.</p>
  <div class="dashboard-buttons">
    <%= link_to 'Gerenciar Categorias', categories_path, class: 'btn-primary' %>
    <%# O botão para Livros apontará para uma rota futura %>
    <%= link_to 'Gerenciar Livros', books_path, class: 'btn-primary' %>
  </div>
<% end %>